<?php

declare(strict_types=1);

namespace LTS\PHPQA\Arkitect;

/**
 * The PHPArkitect config `bin/arkitect-rule` hands the phar. It loads the
 * project's resolved entry config into a scratch `Config`, collects every rule
 * that config registered, and re-adds them all against the one probed
 * directory. The rules are the project's; only where they look changes, so a
 * project entry config that hard-codes its class set to `src/` is probed as
 * readily as the shipped one.
 *
 * Only arkitect's public config API is used (`Config::getClassSetRules()`,
 * `ClassSetRules::getRules()`); no rule is inspected or named. The paths are
 * exported with `var_export`, never interpolated.
 *
 * @internal
 */
final readonly class ProbeConfigRenderer
{
    public function render(string $entryConfig, string $probedDir): string
    {
        $entry = var_export($entryConfig, true);
        $dir   = var_export($probedDir, true);

        return <<<PHP
            <?php

            declare(strict_types=1);

            // Generated by php-qa-ci bin/arkitect-rule on every run; not for editing.
            // The rules of {$entry}, every class set replaced by the probed directory.

            use Arkitect\\ClassSet;
            use Arkitect\\CLI\\Config;

            return static function (Config \$config): void {
                \$project = new Config();
                (require {$entry})(\$project);

                \$rules = [];
                foreach (\$project->getClassSetRules() as \$classSetRules) {
                    foreach (\$classSetRules->getRules() as \$rule) {
                        \$rules[] = \$rule;
                    }
                }

                if ([] === \$rules) {
                    throw new RuntimeException('The entry config ' . {$entry} . ' registered no rule, so no rule could fire.');
                }

                \$config->add(ClassSet::fromDir({$dir}), ...\$rules);
            };

            PHP;
    }
}
