language: php
git:
  depth: false
php:
- 7.0
- 7.1
- 7.2
- hhvm
matrix:
  allow_failures:
  - php: 7.0
  - php: hhvm
before_script: bash -x .travis.bash
script: phpUnitQuickTests=0 phpUnitCoverage=0 bin/qa
notifications:
  slack:
    on_success: change
    rooms:
      - secure: f7iIo36ULJxc8eFbO5dnI8Ql7mXkNU7WEGpwA1mfL/imdDiMB3aWAJsqH8Re0Px8CUpeqTuWetenct9NMKYj95BLaMnpLhkcYK6Bv7frBGrkwEtHPfhVTE1NZA05fpQTgEMMwaC4lBA0YgFvwkwox+cVN/6XgE/nkhhXtxBt8nDvlSxTRy6NO+9td6SdKsg3TQFkm7S0Tp8GAh0q3ZGKHNy9beXh4MiJ6wjtla0mbUyJwDAa37q64izLVU+k4HHWIFRhU2R0J5hal8XbUZeJTmJcNjKAkVoJl9rjo8Fyv4yuOjgoH3885RtIzvleaRyJaqAWjCturX7qTr1qMzWO6adgm/c7cuf5a96Tp+CPPdlxENDEseAWTfBVP83xkHWODDlsD+RJ7GU/RTwRLJlt4AhtohYgjHylmAEA1XihMtnwP1iOzSuDn9zc6OyIEfYvP4sDQkav5/9ZyUyAio+Wy1GCKrPHbQ6un+K72KF47D6eNLRBNbh/0HG6z8d8khReeUpj+dEwF8AaXluz3MAaNBce86+WmEcdPrO73Coqf/dXmNL3L1At8OKoe2aU7mP3o09HVS0+2It32f/sq9e4wHosrW4y9Ivj+JecUOvV4wPDZ/Nh2n4SLc59r0BBP8JyThibpuz3gdCpYo31MzDgTUtV7DxAzXzqx/uHQ5XBOVg=
