<?php

declare(strict_types=1);

namespace LTS\PHPQA\Pipeline\Lane\PhpCsFixer;

use LTS\PHPQA\Pipeline\Config\IgnoredPaths;

/**
 * The source of a PHP CS Fixer config that is the project's resolved
 * php_cs.php with its ignored paths taken out of the finder.
 *
 * The lane runs the fixer with `--path-mode=intersection`, in which the paths
 * on the command line only narrow what the config's finder yields (verified in
 * the shipped phar's ConfigurationResolver::resolveFinder()), so an exclusion
 * has to be in the finder to survive. Putting it in the shipped php_cs.php or
 * php_cs_finder.php would lose it for every project that has copied either
 * into qaConfig/; wrapping whatever config resolves keeps it for all of them,
 * as the PHPStan lane's wrapper neon does.
 *
 * The project's config is required inside a closure so its variables cannot
 * collide with the wrapper's. The finder is wrapped rather than given a
 * notPath(): a project finder may be any iterable, rooted anywhere, and a real
 * path comparison is right for all of them. Each iteration starts afresh, so
 * the finder can be read more than once.
 *
 * @internal
 */
final readonly class IgnoredPathsConfig
{
    public function source(string $projectConfig, IgnoredPaths $ignored): string
    {
        $real = array_map(static fn (string $path): string => file_exists($path) ? \Safe\realpath($path) : $path, $ignored->absolute);

        return \sprintf(
            <<<'PHP_WRAP'
                <?php

                declare(strict_types=1);

                // Generated by php-qa-ci's phpCsFixer lane on every run; edits are overwritten.
                // The project's resolved PHP CS Fixer config, less its withIgnoredPaths().

                $config = (static fn (): mixed => require %s)();

                $config->setFinder(new class ($config->getFinder(), %s) implements IteratorAggregate {
                    public function __construct(private readonly iterable $finder, private readonly array $ignored)
                    {
                    }

                    public function getIterator(): Generator
                    {
                        foreach ($this->finder as $key => $file) {
                            $path = $file->getRealPath();
                            $path = false === $path ? $file->getPathname() : $path;
                            foreach ($this->ignored as $ignored) {
                                if ($path === $ignored || str_starts_with($path, $ignored . '/')) {
                                    continue 2;
                                }
                            }

                            yield $key => $file;
                        }
                    }
                });

                return $config;

                PHP_WRAP,
            var_export($projectConfig, true),
            var_export($real, true),
        );
    }
}
