<?php

declare(strict_types=1);

namespace LTS\PHPQA\Tests\Small;

use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\Attributes\Small;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

use function Safe\file_get_contents;
use function Safe\json_decode;
use function Safe\scandir;

/**
 * Every executable shipped under bin/ must be declared in composer.json's "bin"
 * list, and every declared entry must exist. Composer only links declared
 * entries into a consumer's bin dir, so an undeclared executable is invisible to
 * the consumer: the pipeline fragment that invokes it then fails with
 * "Could not open input file". Conversely a declared-but-missing entry makes
 * Composer print "Skipped installation of bin" on every install.
 *
 * @internal
 */
#[CoversNothing]
#[Small]
final class ComposerBinManifestTest extends TestCase
{
    /** Files under bin/ that are support files, not consumer-facing executables. */
    private const array NON_EXECUTABLE_SUPPORT_FILES = [
        'bootstrap.php',
        'lib-redirect-stub.inc.bash',
    ];

    private const string COMPOSER_PROXY_BANNER = 'Proxy PHP file generated by Composer';

    #[Test]
    public function everyShippedExecutableIsDeclaredAndEveryDeclaredEntryExists(): void
    {
        $root     = \dirname(__DIR__, 2);
        $composer = json_decode(file_get_contents($root . '/composer.json'), true);
        self::assertIsArray($composer);
        self::assertIsArray($composer['bin'] ?? null, 'composer.json must declare a "bin" list');
        $declared = $composer['bin'];
        self::assertContainsOnlyString($declared);

        $shipped = $this->shippedBinFiles($root);
        self::assertNotSame([], $shipped, 'no shipped executables found under bin/');

        $undeclared = array_values(array_diff($shipped, $declared));
        $missing    = array_values(array_diff($declared, $shipped));

        self::assertSame([], $undeclared, 'Executables in bin/ not declared in composer.json "bin" (consumers cannot see them)');
        self::assertSame([], $missing, 'composer.json "bin" entries with no file under bin/');
    }

    /**
     * bin/ also holds the composer bin proxies of this package's OWN dev
     * dependencies (phpunit, parallel-lint, ...). They are generated on install,
     * carry Composer's proxy banner, and are never part of the manifest.
     *
     * @return list<string> repo-relative paths, e.g. `bin/qa`
     */
    private function shippedBinFiles(string $root): array
    {
        $shipped = [];
        foreach (scandir($root . '/bin') as $name) {
            self::assertIsString($name);
            $path = $root . '/bin/' . $name;
            if (!is_file($path)) {
                continue;
            }
            if (\in_array($name, self::NON_EXECUTABLE_SUPPORT_FILES, true)) {
                continue;
            }

            if (str_contains(file_get_contents($path), self::COMPOSER_PROXY_BANNER)) {
                continue;
            }

            $shipped[] = 'bin/' . $name;
        }

        return $shipped;
    }
}
