exclude:
  - */magento/magento-composer-installer/*
  - */magento/zendframework1/*
  - */magento/framework/*
  - */magento/module-config/*
  - */magento/module-deploy/*
  - */magento/module-media-storage/*
  - */magento/module-require-js/*
  - */magento/module-store/*
  - */magento/module-ui/*
  - */magento/module-user/*
  - */magento/module-email/*
  - */magento/module-variable/*
  - */magento/module-backend/*
  - */magento/module-translation/*
  - */magento/module-developer/*
  - */magento/module-authorization/*
  - */magento/module-quote/*
  - */magento/module-catalog-inventory/*
  - */magento/module-eav/*
  - */magento/module-catalog/*
  - */magento/module-page-cache/*
  - */magento/module-url-rewrite/*
  - */magento/module-cms-url-rewrite/*
  - */magento/module-catalog-url-rewrite/*
  - */magento/module-cms/*
  - */magento/module-import-export/*
  - */magento/module-customer/*
  - */magento/module-security/*
  - */magento/module-integration/*
  - */magento/module-widget/*
  - */magento/module-theme/*
  - */magento/module-rule/*
  - */magento/module-catalog-rule/*
  - */magento/module-reports/*
  - */magento/module-sales-rule/*
  - */magento/module-tax/*
  - */magento/module-downloadable/*
  - */magento/module-gift-message/*
  - */magento/module-directory/*
  - */magento/module-sales/*
  - */magento/module-shipping/*
  - */magento/module-checkout/*
  - */magento/module-msrp/*
  - */magento/module-payment/*
  - */magento/module-contact/*
  - */magento/module-rss/*
  - */magento/module-wishlist/*
  - */magento/module-sales-sequence/*
  - */magento/module-grouped-product/*
  - */magento/module-newsletter/*
  - */magento/module-review/*
  - */magento/module-catalog-import-export/*
  - */magento/module-product-alert/*
  - */magento/module-indexer/*
  - */magento/module-cron/*
  - */magento/module-backup/*
  - */magento/language-zh_hans_cn/*
  - */magento/language-pt_br/*
  - */magento/language-nl_nl/*
  - */magento/language-fr_fr/*
  - */magento/language-es_es/*
  - */magento/language-en_us/*
  - */magento/language-de_de/*
  - */magento/theme-frontend-blank/*
  - */magento/theme-frontend-luma/*
  - */magento/theme-adminhtml-backend/*
  - */magento/module-wishlist-analytics/*
  - */magento/module-weee/*
  - */magento/module-webapi/*
  - */magento/module-webapi-security/*
  - */magento/module-version/*
  - */magento/module-vault/*
  - */magento/module-usps/*
  - */magento/module-ups/*
  - */magento/module-tax-import-export/*
  - */magento/module-swatches-layered-navigation/*
  - */magento/module-configurable-product/*
  - */magento/module-swatches/*
  - */magento/module-swagger/*
  - */magento/module-robots/*
  - */magento/module-sitemap/*
  - */magento/module-signifyd/*
  - */magento/module-send-friend/*
  - */magento/module-search/*
  - */magento/module-catalog-search/*
  - */magento/module-sample-data/*
  - */magento/module-sales-inventory/*
  - */magento/module-sales-analytics/*
  - */magento/module-review-analytics/*
  - */magento/module-release-notification/*
  - */magento/module-quote-analytics/*
  - */magento/module-product-video/*
  - */magento/module-persistent/*
  - */magento/module-instant-purchase/*
  - */magento/module-paypal/*
  - */magento/module-offline-shipping/*
  - */magento/module-offline-payments/*
  - */magento/module-new-relic-reporting/*
  - */magento/module-multishipping/*
  - */magento/module-layered-navigation/*
  - */magento/module-grouped-import-export/*
  - */magento/module-cookie/*
  - */magento/module-google-analytics/*
  - */magento/module-google-optimizer/*
  - */magento/module-google-adwords/*
  - */magento/module-fedex/*
  - */magento/module-encryption-key/*
  - */magento/module-downloadable-import-export/*
  - */magento/module-dhl/*
  - */magento/module-customer-import-export/*
  - */magento/module-customer-analytics/*
  - */magento/module-currency-symbol/*
  - */magento/module-configurable-product-sales/*
  - */magento/module-configurable-import-export/*
  - */magento/module-checkout-agreements/*
  - */magento/module-catalog-widget/*
  - */magento/module-catalog-rule-configurable/*
  - */magento/module-catalog-analytics/*
  - */magento/module-captcha/*
  - */magento/module-cache-invalidate/*
  - */magento/module-bundle/*
  - */magento/module-bundle-import-export/*
  - */magento/module-braintree/*
  - */magento/module-authorizenet/*
  - */magento/module-analytics/*
  - */magento/module-advanced-pricing-import-export/*
  - */magento/module-admin-notification/*
  - */magento/module-marketplace/*
  - */magento/composer/*
  - */magento/magento2-base/*
  - */composer/spdx-licenses/*
  - */composer/semver/*
  - */composer/ca-bundle/*
  - */composer/composer/*
  - */zendframework/zend-stdlib/*
  - */zendframework/zend-hydrator/*
  - */zendframework/zend-validator/*
  - */zendframework/zend-escaper/*
  - */zendframework/zend-uri/*
  - */zendframework/zend-loader/*
  - */zendframework/zend-http/*
  - */zendframework/zend-diactoros/*
  - */zendframework/zend-psr7bridge/*
  - */zendframework/zend-servicemanager/*
  - */zendframework/zend-filter/*
  - */zendframework/zend-inputfilter/*
  - */zendframework/zend-form/*
  - */zendframework/zend-eventmanager/*
  - */zendframework/zend-mvc/*
  - */zendframework/zend-math/*
  - */zendframework/zend-crypt/*
  - */zendframework/zend-code/*
  - */zendframework/zend-session/*
  - */zendframework/zend-captcha/*
  - */zendframework/zend-db/*
  - */zendframework/zend-log/*
  - */zendframework/zend-json/*
  - */zendframework/zend-serializer/*
  - */zendframework/zend-di/*
  - */zendframework/zend-config/*
  - */zendframework/zend-view/*
  - */zendframework/zend-i18n/*
  - */zendframework/zend-text/*
  - */zendframework/zend-modulemanager/*
  - */zendframework/zend-console/*
  - */zendframework/zend-server/*
  - */zendframework/zend-soap/*
  - */psr/container/*
  - */psr/log/*
  - */psr/http-message/*
  - */container-interop/container-interop/*
  - */monolog/monolog/*
  - */tedivm/jshrink/*
  - */symfony/polyfill-mbstring/*
  - */symfony/debug/*
  - */symfony/console/*
  - */symfony/process/*
  - */symfony/finder/*
  - */symfony/filesystem/*
  - */symfony/event-dispatcher/*
  - */symfony/dependency-injection/*
  - */symfony/config/*
  - */symfony/stopwatch/*
  - */symfony/polyfill-php72/*
  - */symfony/polyfill-php70/*
  - */symfony/polyfill-php55/*
  - */symfony/polyfill-php54/*
  - */symfony/options-resolver/*
  - */oyejorge/less.php/*
  - */seld/phar-utils/*
  - */seld/jsonlint/*
  - */seld/cli-prompt/*
  - */justinrainbow/json-schema/*
  - */colinmollenhour/credis/*
  - */colinmollenhour/php-redis-session-abstract/*
  - */colinmollenhour/cache-backend-file/*
  - */colinmollenhour/cache-backend-redis/*
  - */temando/module-shipping-m2/*
  - */dotmailer/dotmailer-magento2-extension/*
  - */shopialfb/facebook-module/*
  - */paragonie/random_compat/*
  - */braintree/braintree_php/*
  - */ramsey/uuid/*
  - */league/climate/*
  - */sjparkinson/static-review/*
  - */phpseclib/phpseclib/*
  - */tubalmartin/cssmin/*
  - */pelago/emogrifier/*
  - */squizlabs/php_codesniffer/*
  - */lusitanian/oauth/*
  - */theseer/fdomdocument/*
  - */theseer/tokenizer/*
  - */sebastian/version/*
  - */sebastian/resource-operations/*
  - */sebastian/recursion-context/*
  - */sebastian/object-reflector/*
  - */sebastian/object-enumerator/*
  - */sebastian/global-state/*
  - */sebastian/exporter/*
  - */sebastian/environment/*
  - */sebastian/diff/*
  - */sebastian/comparator/*
  - */sebastian/code-unit-reverse-lookup/*
  - */sebastian/finder-facade/*
  - */sebastian/phpcpd/*
  - */doctrine/instantiator/*
  - */doctrine/lexer/*
  - */doctrine/annotations/*
  - */phpunit/php-text-template/*
  - */phpunit/phpunit-mock-objects/*
  - */phpunit/php-timer/*
  - */phpunit/php-file-iterator/*
  - */phpunit/php-token-stream/*
  - */phpunit/php-code-coverage/*
  - */phpunit/phpunit/*
  - */webmozart/assert/*
  - */phpdocumentor/reflection-common/*
  - */phpdocumentor/type-resolver/*
  - */phpdocumentor/reflection-docblock/*
  - */phpspec/prophecy/*
  - */phar-io/version/*
  - */phar-io/manifest/*
  - */myclabs/deep-copy/*
  - */pdepend/pdepend/*
  - */phpmd/phpmd/*
  - */ircmaxell/password-compat/*
  - */friendsofphp/php-cs-fixer/*