#!/usr/bin/env bash
# Shared consumer-write helpers for php-qa-ci deploy scripts.
#
# OWNERSHIP MODEL (binding decision):
#   Artefacts php-qa-ci deploys into a consumer project (skills, agents, hooks,
#   generated agent definitions, git hooks) are php-qa-ci-OWNED. Consumers must
#   NOT hand-edit the deployed copies — they customise behaviour through their
#   own qaConfig/ files, never by editing a vendored/deployed artefact.
#
#   Because they are owned, the deploy scripts overwrite them UNCONDITIONALLY
#   and CONSISTENTLY — there is exactly one mechanism, not the previous mix of
#   signature checks, interactive prompts, and no-check-at-all. When an existing
#   target differs from what we are about to write, we print a single
#   informational "overwriting" line (never a prompt). Identical content writes
#   silently (no churn note).
#
#   Deployed artefacts should themselves carry a generated-file header comment
#   stating that they are managed by php-qa-ci and will be overwritten, so a
#   reader who opens the deployed copy is told not to hand-edit it.
#
# This file is sourced, not executed. It defines functions only.

# install_owned_file <src> <dst> [label]
#   Install one php-qa-ci-OWNED file, overwriting unconditionally. Emits an
#   informational notice only when an existing target's bytes differ.
install_owned_file() {
    local src="$1" dst="$2"
    local label="${3:-$(basename "$dst")}"
    if [[ -f "$dst" ]] && ! cmp -s "$src" "$dst"; then
        echo "  ℹ️  Overwriting existing $label (php-qa-ci-owned — customise via qaConfig/, do not edit this file): $dst"
    fi
    cp "$src" "$dst"
}

# install_owned_tree <src_dir> <dst_dir> [label]
#   Directory variant (e.g. a skill directory). Overwrites unconditionally;
#   emits the informational notice when the existing tree differs. The
#   destination is guarded with :? so a mis-set/empty variable can never turn
#   the remove-then-copy into an rm -rf of an unintended path.
install_owned_tree() {
    local src="$1" dst="$2"
    local label="${3:-$(basename "$dst")}"
    if [[ -d "$dst" ]] && ! diff -rq "$src" "$dst" > /dev/null; then
        echo "  ℹ️  Overwriting existing $label (php-qa-ci-owned — customise via qaConfig/, do not edit these files): $dst"
    fi
    rm -rf "${dst:?install_owned_tree: refusing to remove an empty destination}"
    cp -r "$src" "$dst"
}
