#!/usr/bin/env bash
# Infection — mutation testing (measures whether the TEST suite actually kills
# injected faults; the MSI/Covered-Code-MSI floors are the ratchet's quality gate).
#
# SELF-CONTAINED + KERNEL-BOOTING-SUITE-SAFE.
#
# This step must work BOTH as part of the full `bin/qa` pipeline AND standalone
# via `bin/qa -t infection` (the single-tool path bypasses the `useInfection`
# gate in allTestingTools, so it can be invoked directly). To make that safe:
#
#   1. Infection needs code coverage (coverage-xml + the junit log). In the full
#      pipeline the phpunit-with-coverage step has already produced it under
#      $varDir/phpunit_logs; standalone there is none. So we DETECT existing
#      coverage and REUSE it, or GENERATE it here with a single phpunit coverage
#      run (no double run when the pipeline already produced it). A failing
#      coverage run fails the step — and that same run proves the suite is green,
#      which is precisely what lets us skip Infection's own initial test run.
#
#   2. We ALWAYS pass --skip-initial-tests. Infection's built-in initial run
#      re-executes the WHOLE suite a second time; for a kernel-booting,
#      DB-coupled Symfony integration suite that redundant threaded pass
#      misbehaves. Coverage is guaranteed present after step 1, so Infection
#      never needs (and never runs) the initial suite. This lets a consuming
#      project drop any bespoke side-script that wrapped Infection with its own
#      coverage + --skip-initial-tests sequence — the harness now does it.
#
# The MSI floors come from setConfig.inc.bash (read from the project's
# qaConfig.inc.bash — mutationScoreIndicator / coveredCodeMSI). The SSoT floor
# stays enforced here; we never narrow or lower it.

# Coverage needs an Xdebug driver. If Xdebug is unavailable we cannot generate
# coverage, so mutation testing cannot run. Skip with a clear message and exit
# cleanly (return 0) — matching how bin/qa reports "infection not available"
# without Xdebug, and how a consumer-side mutation gate skips rather than fails
# on a coverage-less host. (In the full pipeline this branch is normally never
# reached, because setConfig sets useInfection=0 when xdebugEnabled=0 and
# allTestingTools then skips the step entirely; this guard covers the standalone
# `-t infection` invocation, which bypasses that gate.)
if [[ "1" != "${xdebugEnabled:-0}" ]]; then
    echo "Infection: Xdebug is not enabled — cannot generate coverage, so mutation testing cannot run. SKIPPING."
    return 0
fi

infectionPath="$pharDir/infection.phar"
coverageXmlDir="$varDir/phpunit_logs/coverage-xml"

# Resolve the MSI floors HERE, at run time, from the project's SSoT vars
# (qaConfig/qaConfig.inc.bash exports mutationScoreIndicator / coveredCodeMSI).
# setConfig.inc.bash derives infectionMutationScoreIndicator / infectionCoveredCodeMSI
# EARLIER in bin/qa — BEFORE the project override is sourced — so those derived
# vars freeze at the generic defaults (60/80) and would NOT carry the project's
# floor. By the time this tool actually runs the override IS in scope, so prefer
# the project SSoT vars and fall back to the derived values. This keeps the
# monotonic ratchet floor authoritative; never narrow or lower it.
minMsi="${mutationScoreIndicator:-${infectionMutationScoreIndicator}}"
minCoveredMsi="${coveredCodeMSI:-${infectionCoveredCodeMSI}}"

# DETECT vs GENERATE coverage.
#   - Present + non-empty -> the pipeline's phpunit-with-coverage run already
#     produced it: REUSE it (no second phpunit run).
#   - Absent/empty -> generate it here with a single xdebug coverage run. Use
#     $phpBinPath (the xdebug-enabled php), NOT phpNoXdebug — the coverage driver
#     must be loaded. Exit code captured via the `if` condition so a non-zero
#     status does not abort the run under errexit. A failure fails the step (it
#     also proves the suite green) — the usual coverage-then-mutation sequence.
if [[ -d "$coverageXmlDir" && -n "$(ls -A "$coverageXmlDir" 2>/dev/null)" ]]; then
    echo "Infection: reusing existing coverage at $coverageXmlDir (generated by the phpunit step)."
else
    echo "Infection: no coverage found at $coverageXmlDir — generating it (xdebug) before mutation testing."
    echo "           (this also proves the suite is green, which lets Infection skip its initial run)"
    coverageGenExit=0
    if XDEBUG_MODE=coverage "$phpBinPath" -f "$binDir"/phpunit -- \
        -c "$phpUnitConfigPath" \
        --coverage-xml "$coverageXmlDir" \
        --log-junit "$varDir/phpunit_logs/phpunit.junit.xml"; then
        coverageGenExit=0
    else
        coverageGenExit=$?
    fi
    if ((coverageGenExit > 0)); then
        echo "Infection: coverage generation FAILED (phpunit exit $coverageGenExit) — the test suite is not green, so mutation testing cannot proceed."
        tryAgainOrAbort "Infection (coverage generation)"
        # In CI tryAgainOrAbort exits non-zero; interactively it returns so the
        # caller can re-run. Re-source from the top to regenerate coverage.
        return 1
    fi
fi

# Run Infection against the (reused or freshly generated) coverage.
#   - --skip-initial-tests: coverage is guaranteed present; never re-run the
#     kernel-booting suite (see header).
#   - Infection itself runs WITHOUT Xdebug (phpNoXdebug) — it only consumes the
#     coverage we already produced, and dropping Xdebug here is faster, matching
#     the historic behaviour of this step.
#   - The floor flags (--min-msi / --min-covered-msi) are the SSoT ratchet.
#   - The invocation runs inside an `if` CONDITION, so under bin/qa's errexit a
#     non-zero exit does NOT abort the run (errexit is suspended for conditions);
#     it is handled explicitly via the retry loop below.
function runInfection() {
    local extraArgs=( -- )
    if [[ "1" == "${infectionOnlyCovered:-0}" ]]; then
        extraArgs+=( --only-covered )
    fi
    phpNoXdebug -f "$infectionPath" \
        "${extraArgs[@]}" \
        --coverage="$varDir/phpunit_logs" \
        --skip-initial-tests \
        --threads="${infectionThreads}" \
        --configuration="${infectionConfig}" \
        --min-msi="${minMsi}" \
        --min-covered-msi="${minCoveredMsi}" \
        --log-verbosity=all
}

infectionExitCode=99
while ((infectionExitCode > 0)); do
    backupIFS=$IFS
    IFS=$standardIFS

    rm -rf "$varDir"/infection/*
    if runInfection; then
        infectionExitCode=0
    else
        infectionExitCode=$?
    fi

    IFS=$backupIFS
    if ((infectionExitCode > 0)); then
        tryAgainOrAbort "Infection"
    fi
done
