name: PHP QA

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest Ref
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache Vendor
        id: cacheVendor
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('./composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1

  qa:
    name: PHP QA CI
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Run test suite
        run: ./ci.bash
